### ISSUE TITLE
Upstream Policy

### ISSUE THREAD

**Issue by ksqsf** [ksqsf/emacsmoe#3]
* When shall we sync with upstream? (Pull changes from upstream)
* Should we consider getting these changes into the upstream?

**Comment by dgutov** [comment]
@ksqsf Are you looking into how to implement this on GNU/Linux?

That would be required for upstreaming.

**Comment by ksqsf** [comment]
@dgutov Thanks for the info.

I did try to implement it on GNU/Linux back in January, but later distracted by other things. Right now I'm not working on this.
