### ISSUE TITLE
Building on OSX

### ISSUE THREAD

**Issue by jakeprime** [ksqsf/emacsmoe#4]
Hi @ksqsf 

I have been wanting the text shadow feature for so long, I am so excited it is coming!

Sorry if I am jumping the gun here, I know it's still in PR, but I'm just really keen 😄  I have tried to build from the `feature/shadows` branch but it always errors when trying to include `<cairo.h>`. I am on an M1 running Ventura 13.1. This is what I have done:

```sh
$ brew install imagemagick gnutls autoconf automake libx11 automake autoconf libxml2 libgccjit
$ make configure
$ ./configure --with-cairo --with-imagemagick --with-xwidgets --with-native-compilation
$ make install
```

The install runs for a bit and then errors on:

```sh
  CC       xcairo.o
xcairo.c:3:10: fatal error: 'cairo.h' file not found
#include <cairo.h>
         ^~~~~~~~~
1 error generated.
make[1]: *** [xcairo.o] Error 1
make: *** [src] Error 2
```

If I can help in anyway I am happy to spend the time, but this is quite far outside my area of software, so not much expertise I am afraid. I can certainly create a theme or two though, especially if that will help this get merged upstream.

**Comment by ksqsf** [comment]
Thanks! I'm truly encouraged by the fact that there's at least one person other than me who also wants this. 

The compilation error is my fault. I've pushed a fix. It should build now, and you can test it using the following command:

```
src/emacs -q -l moe/shadow-demo.el
```

<img width="672" alt="image" src="https://user-images.githubusercontent.com/23358293/223455170-18950362-bd31-4d0f-8840-8bef8f4df966.png">

Don't hesitate to report any issues you find.

**Comment by jakeprime** [comment]
Thanks so much @ksqsf! It built fine after that fix.

<img width='200px' src='https://user-images.githubusercontent.com/1019036/224841402-da89f503-fdcc-451b-b69f-a6d8a916c016.png' />

I'm going to see how close I can get to [synthwave-x-fluoromachine](https://marketplace.visualstudio.com/items?itemName=webrender.synthwave-x-fluoromachine), but it will take me a while so please don't expect anything soon. I have actually never used Emacs, even though I have wanted to for ages, only because it was missing a glow effect, hence so excited about this feature. Let the learning commence.

The shadow effect is great as it is and enough for me to make the switch, but one thing that would make it even better would be if you could have multiple shadows on the same font? I have no idea if that is easy, impossible, or anywhere inbetween. The styling for synthwave-x-fluoromachine takes advantage of this:

```css
.mtk10 {
  color: #fc199a;
  text-shadow: 0 0 2px #393a33, 0 0 35px #ffffff44, 0 0 10px #fc199a, 0 0 2px #fc199a;
}
```

This allows a nice big glow, but with good close definition like:

<img width='200px' src='https://user-images.githubusercontent.com/1019036/224841245-c1991666-0e5b-4a3c-9b64-25f3362425c0.png' />

**Comment by ksqsf** [comment]
There's no need to rush (I'm also taking my time to fix other issues. :-), and thanks for your endeavor!

Multiple shadows are not hard to draw, but that perhaps will require a deeper change in the face attribute handling code, as it can store information about only one shadow.  So I won't try to do that soon.  I will revisit it and see if it's possible when other issues are fixed.

PS, "big" glow atm does not work as one expects, (a shadow is restricted by a virtual box, and the box can sometimes be too small.)  I'm still working on this.

**Comment by jakeprime** [comment]
Hi, I'm using this every day now, and built a custom theme that does a pretty good job of replicating synthwave-x-fluoromachine. Still more to do, but thought you would be interested to see what I've done with it:

![photo_2023-06-21_23-50-48](https://github.com/ksqsf/emacsmoe/assets/1019036/599d5b77-0aea-401d-a004-c3e08ffedf21)

Thanks again, I love it!

**Comment by ksqsf** [comment]
@jakeprime Wow, thanks for letting me know! Your efforts give me substantial motivation to continue this work and hopefully get it merged into the upstream.

I'm also interested in your theme! Would you mind sharing it? :-)

**Comment by jakeprime** [comment]
Yeah sure this it's in my .dotfiles repo: https://github.com/jakeprime/.dotfiles/tree/main/spacemacs

I couldn't get the shadows to work from the theme file itself, I have to specify it in `dotspacemacs/user-config` in my init file.
