### ISSUE TITLE
#error "Please include config.h first."

### ISSUE THREAD

**Issue by MaxiJP** [ksqsf/emacsmoe#5]
Hiya @ksqsf !

I am very new to Emacs and have been tinkering around a lot with it. I've been trying to compile your features/shadow branch of EmacsMoe with no luck. I seem to be bottle necked when compiling

When running "sudo make -j8", I get a very peculiar error, repeated over multiple files:

![image](https://github.com/ksqsf/emacsmoe/assets/66430740/8e886d89-ccbb-450f-950b-57f9c1422784)

I'm not really sure what it is. I checked the issue from @jakeprime about the use of Cairo, but I don't think that is what is happening here.

If you need any more information, just follow me up and I will tell you! By the way, I apologise in advance if this is a really stupid mistake. I both don't build much stuff from source and also don't have any experience with building or working with Emacs that much.

**Comment by ksqsf** [comment]
Hi! This is indeed a nit. I have pushed a fix (and updated the branch to the current master). I didn't test it, but hopefully it will build now.

**Comment by MaxiJP** [comment]
Hi again!

Thank you so much! It compiles without a sound now and the glowing is working perfectly. Keep up the great work!
